language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - master

matrix:
  fast_finish: true
  allow_failures:
    - php: master
    # allow 7.3 to fail, as pear.php.net is down and it has no cache with missing PEAR packages yet :(
    - php: 7.3

services:
  - memcached
#  - mysql we use mariadb instead installed via addons below
  - postgres

addons:
  mariadb: '10.0'

sudo: required

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y myrepos libpcre3-dev
  - case $(phpenv version-name) in
    "5.6")
       yes "" | pecl install memcache;
       yes "" | pecl install apcu-4.0.11;
       yes "" | pecl install igbinary;
       echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
       phpenv config-rm xdebug.ini;
       ;;
    "7"|"7.0"|"7.1"|"7.2")
       yes "" | pecl install apcu;
       echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
       phpenv config-rm xdebug.ini;
      ;;
    "7.3"|"master")
       echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
      ;;
    esac
  - case $(phpenv version-name) in
    "5.6")
       composer require 'phpunit/phpunit:~5.7';
       ;;
    "7"|"7.0")
       composer require 'phpunit/phpunit:~6';
       ;;
    *)
       composer require 'phpunit/phpunit:~7';
      ;;
    esac
  #- php -m
  - php -i
  - sed 's/^update = git stash -q/update = \#git stash -q/g' .mrconfig
  - mr --trust-all --stats up
  - (cd activesync; mr --trust-all --stats up)
  # create data directory
  - sudo mkdir /var/lib/egroupware
  - sudo chown travis /var/lib/egroupware
  - ln -s /var/lib/egroupware/header.inc.php

script:
  # install egroupware using MariaDB as domain "default"
  # and add an admin user "demo" with password "guest"
  - php doc/rpm-build/post_install.php --domain default
    --source_dir `pwd` --start_db '' --autostart_db '' --start_webserver '' --webserver_user ''
    --admin_user demo --admin_passwd guest --admin_email noreply@example.com
  # disable PostgreSQL install as it fails in Travis with Fatal error: Call to unimplemented native function pg_set_client_encoding
  # install egroupware using PostgreSQL as domain "pgsql", need some specific handling we can not create users via sql
  #- psql -U postgres -c 'create database egroupware';
  # disable postgres install for hhvm, as there is no psql extension
  #- test $(phpenv version-name) = 'hhvm' ||
  #  php doc/rpm-build/post_install.php --domain pgsql --db_type pgsql --db_port 5432 --db_user postgres --db_pass ''
  #  --source_dir `pwd` --start_db '' --autostart_db '' --start_webserver '' --webserver_user ''
  # install egroupware with LDAP for account and MySQL as domain "ldap"
  #- php doc/rpm-build/post_install.php --domain ldap --db_name ldap --db_user ldap
  #  --account-auth ldap --ldap_suffix dc=local --ldap_admin 'cn=admin,$suffix' --ldap_admin_pw secret
  #  --source_dir `pwd` --start_db '' --autostart_db '' --start_webserver '' --webserver_user ''
  # Ubuntu has problems with #!/usr/bin/env php -dapc.enable=1, it stalls forever
  - vendor/bin/phpunit -c doc -dapc.enable_cli=1
  # do not run syntax check for hhvm, as it always fails / get terminated after 10m
  - test $(phpenv version-name) = 'hhvm' || ./doc/php_syntax_check.sh

cache:
  directories:
    - $HOME/.composer/cache
