language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7

#env:
  #matrix:
    #- LOWEST_DEPS=""
    #- LOWEST_DEPS="--prefer-lowest"

#services:
#  - mysql
#  - postgres

sudo: false

before_script:
  # - mysql -e 'create database egroupware'
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  #- composer update --prefer-source $LOWEST_DEPS
  - echo PHP $(phpenv version-name)
  # remove certain files failing php syntax checks in PHP 7.0
  - test $(phpenv version-name) = "7.0" && rm -f phpgwapi/inc/horde/Horde/String.php

script:
  - find . -name "*.php" | xargs -n1 php -l
  #- ./vendor/bin/sabre-cs-fixer fix . --dry-run --diff

cache:
  directories:
    - $HOME/.composer/cache