language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

#env:
  #matrix:
    #- LOWEST_DEPS=""
    #- LOWEST_DEPS="--prefer-lowest"

services:
  - memcached
#  - mysql
#  - postgres

addons:
  mariadb: '10.0'

sudo: required
dist: trusty
# this fixes hhvm builds according to https://docs.travis-ci.com/user/languages/php#HHVM-versions-on-Trusty
group: edge

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y myrepos libpcre3-dev
  - case $(phpenv version-name) in
    "5.4")
       yes "" | pecl install memcache;
       echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
       yes "" | pecl install apcu-4.0.11;
       echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
       yes "" | pecl install igbinary;
       echo "extension=igbinary.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
       echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
       ;;
    "5.5"|"5.6")
       yes "" | pecl install memcache;
       yes "" | pecl install apcu-4.0.11;
       yes "" | pecl install igbinary;
       echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
       ;;
    "7")
       yes "" | pecl install apcu;
       echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
       ;;
    "hhvm")
       ;;
    esac
  #- php -m
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  #- composer update --prefer-source $LOWEST_DEPS
  - curl https://svn.stylite.de/fix_mrconfig 2>/dev/null | php
  - mr --trust-all --stats up
  - (cd activesync; mr --trust-all --stats up)
  # installing phpunit in version suitable for used PHP version
  - composer update phpunit/phpunit
  # create data directory
  - sudo mkdir /var/lib/egroupware
  - sudo chown travis /var/lib/egroupware

script:
  # install egroupware
  - php doc/rpm-build/post_install.php
    --source_dir `pwd` --start_db '' --autostart_db '' --start_webserver '' --webserver_user ''
  #- mysql -uroot -e 'show tables' egroupware
  # Ubuntu has problems with #!/usr/bin/env php -dapc.enable=1, it stalls forever
  - php -dapc.enable_cli=1 doc/test-cli.php
  - ./doc/php_syntax_check.sh

cache:
  directories:
    - $HOME/.composer/cache